service: my-products-service

# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "3"

custom:
  serverless-auto-swagger:
    apiType: "httpApi"
    generateSwaggerOnDeploy: true
    typefiles: ["./src/types/api-types.d.ts"]

# Add the serverless-webpack plugin
plugins:
  - serverless-auto-swagger
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    PG_HOST: ${PG__HOST}
    PG_PORT: ${PG__PORT}
    PG_DATABASE: ${PG__DATABASE}
    PG_USERNAME: ${PG__USERNAME}
    PG_PASSWORD: ${PG__PASSWORD}
    SNS_ARN: { Ref: SNSTopic }
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: "*"
    - Effect: "Allow"
      Action: "sns:*"
      Resource:
        Ref: SNSTopic
  apiGateway:
    minimumCompressionSize: 1024 #Enable gzip compression for responses > 1 KB

resources:
  Resources:
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: my-product-service-topic-gleb
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: ${FIRST__EMAIL}
        Protocol: email
        TopicArn:
          Ref: SNSTopic
    SNSSubscriptionFiltered:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: ${SECOND__EMAIL}
        Protocol: email
        TopicArn:
          Ref: SNSTopic
        FilterPolicy:
          image:
            - true

functions:
  fillDb:
    handler: pg-client-lambda.invoke
  getProductsList:
    handler: getProductsList.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
  getProductsById:
    handler: getProductsById.getProductsById
    events:
      - httpApi:
          path: /products/{productId}
          method: get
  postProduct:
    handler: postProduct.postProduct
    events:
      - httpApi:
          path: /products
          method: post
          bodyType: "Product"
  catalogBatchProcess:
    handler: catalogBatchProcess.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn: arn:aws:sqs:eu-west-1:789720210154:my-import-service-queue-gleb
